#[Ссылка на Tableau](https://public.tableau.com/app/profile/sergey.krutiko/viz/Book1_16502897868380/sheet12?publish=yes)

#[Презентация PDF](https://drive.google.com/file/d/10BGQVNXmYSpFeEfPyEevpAH7QMqmzV2Z/view?usp=sharing)

#[Презентация PPTX](https://docs.google.com/presentation/d/1LDynE66Y7SuiKp_Z6Cdoskk7p6DfprEy/edit?usp=sharing&ouid=110330816513284098819&rtpof=true&sd=true)

In [ ]:
#%%sh
#pip install -q dash
#pip install -q dash_core_components
#pip install -q dash_html_components
#pip install -q dash_table

In [ ]:
#%%sh
# get ngrok
#curl -O https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
#unzip ngrok-stable-linux-amd64.zip

In [ ]:
# launch ngrok
#get_ipython().system_raw('./ngrok http 8050 &')

In [ ]:
#!python dash_app.py

In [ ]:
#%%sh
# get url with ngrok
#curl -s http://localhost:4040/api/tunnels | python3 -c "import sys, json; print(json.load(sys.stdin)['tunnels'][0]['public_url'])"

# Обработка данных

In [ ]:
# импортируем библиотеки
import pandas as pd
from sqlalchemy import create_engine

db_config = {'user': 'praktikum_student', # имя пользователя
            'pwd': 'Sdf4$2;d-d30pp', # пароль
            'host': 'rc1b-wcoijxj3yxfsf3fs.mdb.yandexcloud.net',
            'port': 6432, # порт подключения
            'db': 'data-analyst-zen-project-db'} # название базы данных

connection_string = 'postgresql://{}:{}@{}:{}/{}'.format(db_config['user'],
                                                db_config['pwd'],
                                                db_config['host'],
                                                db_config['port'],
                                                db_config['db'])

engine = create_engine(connection_string)

query = ''' SELECT * 
        FROM dash_visits
        '''
dash_visits = pd.io.sql.read_sql(query, con = engine)

pd.io.sql.read_sql(query, con = engine)

/usr/local/lib/python3.7/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)

,record_id,item_topic,source_topic,age_segment,dt,visits
0,1040597,Деньги,Авто,18-25,2019-09-24 18:32:00,3
1,1040598,Деньги,Авто,18-25,2019-09-24 18:35:00,1
2,1040599,Деньги,Авто,18-25,2019-09-24 18:54:00,4
3,1040600,Деньги,Авто,18-25,2019-09-24 18:55:00,17
4,1040601,Деньги,Авто,18-25,2019-09-24 18:56:00,27
...,...,...,...,...,...,...
30740,1071337,Юмор,Финансы,36-40,2019-09-24 18:57:00,2
30741,1071338,Юмор,Финансы,36-40,2019-09-24 19:00:00,1
30742,1071339,Юмор,Финансы,41-45,2019-09-24 18:54:00,1
30743,1071340,Юмор,Финансы,41-45,2019-09-24 18:56:00,1
30744,1071341,Юмор,Финансы,41-45,2019-09-24 19:00:00,1

In [ ]:
# dash_visits.to_csv('dash_visits', index = False)

In [ ]:
# сохраняем df указывая путь
dash_visits.to_csv('/content/drive/MyDrive/Colab Notebooks/11_Автоматизация_Проект/dash_visits.csv', index = False)

Далее в Tableau мы привяжемся к Google диску, указав путь

Посмотрим данные здесь, чтоб объективно ориентироваться в Tableau.

In [ ]:
dash_visits

,record_id,item_topic,source_topic,age_segment,dt,visits
0,1040597,Деньги,Авто,18-25,2019-09-24 18:32:00,3
1,1040598,Деньги,Авто,18-25,2019-09-24 18:35:00,1
2,1040599,Деньги,Авто,18-25,2019-09-24 18:54:00,4
3,1040600,Деньги,Авто,18-25,2019-09-24 18:55:00,17
4,1040601,Деньги,Авто,18-25,2019-09-24 18:56:00,27
...,...,...,...,...,...,...
30740,1071337,Юмор,Финансы,36-40,2019-09-24 18:57:00,2
30741,1071338,Юмор,Финансы,36-40,2019-09-24 19:00:00,1
30742,1071339,Юмор,Финансы,41-45,2019-09-24 18:54:00,1
30743,1071340,Юмор,Финансы,41-45,2019-09-24 18:56:00,1
30744,1071341,Юмор,Финансы,41-45,2019-09-24 19:00:00,1